name: PR-Trigger
# triggers
on: 
 pull-request :
  types: [opened, reopened]
# stages
jobs:
  my-job: #stage
    runs-on: ubuntu-latest # agent This is github hosted runner
    steps:
     # this give us data of full even triggeres
      - name: event triggered data #steps1
        run: |
          cat "$GITHUB_EVENT_PATH"
          echo "The action was: $(jq -r '.action' "$GITHUB_EVENT_PATH")"
